### ISSUE TITLE
implement Join and Merge for iterators?

### ISSUE THREAD

**Issue by akriegman** [yoshuawuyts/futures-concurrency#10]
Hi, huge fan of what this crate has to offer. I'm wondering if anyone's thought about implementing these traits for iterators? Is there a technical reason why that would be difficult or is it just that no one has done it yet? I could try my hand at it.

I'm thinking something with a signature like:
```rust
impl<T, F, O> Join for T
where
    T: Iterator<Item = F>,
    F: Future<Output = O>,
{
    type Output = std::vec::IntoIter<O>;
    ...
}
```
Although already several questions are raised just writing this out. Would we want `T: Iterator` or `T: IntoIterator`? In the second case we would conflict with implementations for `Vec` and arrays, so probably `Iterator`. It would be nice to cover more types with one generic implementation, but I don't think we could give one implementation that is satisfying for iterators, vecs, and arrays.

The next question is the output type. On the one hand it would be nice to have the output be the same kind of thing as the input, so `<T as Join>::Output: Iterator<Item = O>`. On the other hand, joining all the futures would probably require allocating the results into a vec, and the `IntoIter` struct contains a vec, meaning that if the user just wants a vec they have to do a `.collect()` (which I think would get optimized away), making the `IntoIter`'s existence pointless. It would be nice to give the user back the same kind of thing they put in, but if it's secretly a vec behind the scenes then it may better to give them that and leave them the option to use `.into_iter()` to get an iterator.

Personally I would want to return an iterator. In  my code I'm using `futures::future::join_all` and `tap`, and I'm writing over and over again:
```rust
.pipe(join_all)
.await
.into_iter()
```
it would be slightly better if I could write:
```rust
.join()
.await
.into_iter()
```
and slightly better still:
```rust
.join()
.await
```
But maybe in someone else's use case they want a `Vec` more often than they want an iterator.

Anyways, I like this crate and I hope that one day it goes mainstream :).

**Comment by yoshuawuyts** [comment]
Thanks for opening this issue! I agree we should have something for iterators, but I'm not sure this crate is necessarily the best place for it. The plan is currently to continue work on the `parallel-stream` crate, whose goal it is to provide a rayon-like API for parallel async iteration.

I hope that answers your questions!
