### ISSUE TITLE
Where is `TryMerge` :-)?

### ISSUE THREAD

**Issue by Hywan** [yoshuawuyts/futures-concurrency#146]
That's a new game. `TryMerge` has a red and white shirt, and woolly hat. We see `TryMerge` in the doc', but not in the implementation. Hence the question: where is `TryMerge` ;-)?

**Comment by yoshuawuyts** [comment]
Oh I didn't realize we had TryMerge in the docs — we, I, didn't end up implementing it.

I don't believe that's necessary tbh. Because async iteration combinators are lazy you can short-circuit based on the data quite easily. Just for-loop and `?` and the iteration can be interrupted.

**Comment by Hywan** [comment]
Yup, got it :-). I though there was something I misunderstood here. Thanks!
