### ISSUE TITLE
Use `Waker::clone_from` internally

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/futures-concurrency#160]
Now that https://github.com/rust-lang/rust/pull/96979 has been merged, we should use `Waker::clone_from` in our `set_waker` functions to remove reduce unnecessary clones. If done right, then from now on we'll typically only clone-on-wake the first time our concurrency types are polled.

This should be relatively simple to implement, so anyone who wants to pick it up should feel free to. It would also be interesting to bench this on nightly, which should have these changes starting ~tomorrow.

**Comment by miguelraz** [comment]
Taking a crack at this! First contribution and learning the ropes here.

Kind of stuck at this stage:

```rust
        Waker::clone_from(&mut self.parent_waker.unwrap(), parent_waker);
```

Matching on `self.parent_waker` didn't make sense either. Could you provide a tip on how to proceed here?
