### ISSUE TITLE
Implement better capacity in our group structures

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/futures-concurrency#169]
https://github.com/yoshuawuyts/futures-concurrency/pull/168 fixes the immediate insertion time issues of `FutureGroup::insert` - however the code is, how should I say this, not great?

We need to implement our own exponential capacity algorithm. This means implementing a `reserve` method which ensures there is enough capacity. And then making sure that if we run out of capacity we always double our space. We may even want to rename some of our existing `resize` methods to `reserve`, since they don't take items where [`Vec::resize`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.resize) does.

This probably needs to be an immediate follow-up to #168; I don't think we should release a new version without it.

**Comment by yoshuawuyts** [comment]
As I said in: https://github.com/yoshuawuyts/futures-concurrency/issues/175

> @matheus-consoli are you still ok to file that PR? If not, feel free to re-assign this to me!

**Comment by matheus-consoli** [comment]
yes! sorry for the delay, busy week!
