### ISSUE TITLE
Declare minimum support rust version in Cargo manifest

### ISSUE THREAD

**Issue by Awfa** [yoshuawuyts/futures-concurrency#180]
Today, this crate doesn't declare the [msrv](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) in the `Cargo.toml`.

This can lead to more confusing errors when trying to compile with an older Rust compiler, and when trying to find the right release that would work with an older Rust compiler.

This would likely need a pipeline change as well, so the CI verifies the declared msrv. There seems to be notes on that [here](https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version).

**Comment by matheus-consoli** [comment]
hi @Awfa, i think we should definitely do it, thanks for pointing this out!
