### ISSUE TITLE
implement `(a, b, c).race()` in this crate, or somewhere else?

### ISSUE THREAD

**Issue by alsuren** [yoshuawuyts/futures-concurrency#6]
In https://blog.yoshuawuyts.com/futures-concurrency-3/ there is mention of Future::race extension method in async_std.

There is also a suggestion that there could be an extension trait that's implemented for tuples, similar to how Merge works currently in this crate: https://docs.rs/futures-concurrency/latest/futures_concurrency/trait.Merge.html#impl-Merge-for-(S0%2C%20S1%2C%20S2%2C%20S3)

The post also says: 

> In this post we're going to take a look at how this mode of concurrency works, take a closer look at the issues select! {} has, discuss Stream::merge as an alternative, and finally we'll look at what the ergonomics might look like in the future. This post is part of the "Futures Concurrency" series. You can find all library code mentioned in this post as part of the [futures-concurrency](https://docs.rs/futures-concurrency) crate.

I find the idea of a `race` extension method really compelling, and have told all of my workmates about the blog post, but there doesn't seem to be an implementation of it yet. If someone wanted to implement this trait, would this repo be a reasonable place to put it?

**Comment by yoshuawuyts** [comment]
Hi! yeah sorry, it's not yet implemented. I'm going to try implementing this now, let me see what I can do (:

**Comment by yoshuawuyts** [comment]
Published 3.0 which has the `race` combinators!
